[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools_scm[toml]>=8.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "as_op_doubleweave"
dynamic = ["version"]
description = "Convert weaving patterns to overshot-patterned double weave"
readme = "README.md"
dependencies = [
  "dtx_to_wif >= 3.0",
]
authors = [
  { name="Russell Owen", email="r3owen@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
  "pre-commit >= 3.8",
  "pytest >= 8.3",
]

[project.scripts]
as_op_doubleweave = "as_op_doubleweave.entry_points:run_as_op_doubleweave"
filter_patterns = "as_op_doubleweave.entry_points:run_filter_pattern"

[project.urls]
Homepage = "https://github.com/r-owen/as_op_doubleweave"
Issues = "https://github.com/r-owen/as_op_doubleweave/issues"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.isort]
profile = "black"

[tool.setuptools_scm]
write_to = "src/as_op_doubleweave/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""
